# Generated by Django 6.0.1 on 2026-03-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default='Unknown', max_length=100)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('upload', 'Upload Manual'), ('device', 'Thermal Device')], default='upload', max_length=20)),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('csv_left', models.FileField(blank=True, null=True, upload_to='scans/')),
                ('csv_right', models.FileField(blank=True, null=True, upload_to='scans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FootRegionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('toe', 'Toe / Jari'), ('forefoot', 'Forefoot / Depan'), ('midfoot', 'Midfoot / Tengah'), ('heel', 'Heel / Tumit')], max_length=10)),
                ('side', models.CharField(choices=[('left', 'Kiri'), ('right', 'Kanan')], max_length=5)),
                ('mean_temp', models.FloatField(default=0)),
                ('max_temp', models.FloatField(default=0)),
                ('delta_temp', models.FloatField(default=0)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_analyses', to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='ExplainabilityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heatmap_left', models.ImageField(blank=True, null=True, upload_to='heatmaps/')),
                ('heatmap_right', models.ImageField(blank=True, null=True, upload_to='heatmaps/')),
                ('overlay_left', models.ImageField(blank=True, null=True, upload_to='overlays/')),
                ('overlay_right', models.ImageField(blank=True, null=True, upload_to='overlays/')),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explainability', to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(choices=[('DM', 'Diabetes Mellitus'), ('DPN', 'Diabetic Peripheral Neuropathy'), ('PAD', 'Peripheral Arterial Disease'), ('Normal', 'Normal')], max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('risk_level', models.CharField(choices=[('Low', 'Rendah'), ('Moderate', 'Sedang'), ('High', 'Tinggi')], default='Low', max_length=10)),
                ('prob_dm', models.FloatField(default=0)),
                ('prob_dpn', models.FloatField(default=0)),
                ('prob_pad', models.FloatField(default=0)),
                ('model_version', models.CharField(default='rule-based-v1', max_length=50)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='scanner.scan')),
            ],
        ),
        migrations.CreateModel(
            name='ThermographicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_mean', models.FloatField(default=0)),
                ('left_max', models.FloatField(default=0)),
                ('left_min', models.FloatField(default=0)),
                ('right_mean', models.FloatField(default=0)),
                ('right_max', models.FloatField(default=0)),
                ('right_min', models.FloatField(default=0)),
                ('delta_mean', models.FloatField(default=0)),
                ('symmetry_index', models.FloatField(default=0)),
                ('asymmetry_max', models.FloatField(default=0)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='scanner.scan')),
            ],
        ),
    ]
